Added API auth and JWT auth for user decorators
stopstalk/stopstalk-deployment pull request #425
Opened 2020-09-26 14:01 UTC by manav1403

**Decorators --**

- > **@check_api_token** -- checks whether the request is having a valid API token or not
- > **@check_api_userauth** -- signifies authentication is required and validates the JWT token passed in the header for user authentication

**Ednpoints-- [./user/login_token/]**
-  @withparameter email and password return {token : ''} if valid credentials
-  @withparameter token returns the new refresh token

2020-09-26 16:45 UTC, raj454raj requested changes

2020-09-26 16:45 UTC, raj454raj commented on models/db.py
> +userjwt = AuthJWT(auth, secret_key= current.jwt_secret, user_param="email")
```suggestion
userjwt = AuthJWT(auth, secret_key=current.jwt_secret, user_param="email")
```

2020-09-26 17:00 UTC, manav1403 commented on modules/utilities.py
> +        return function(*args, **kwargs)
yes because if its not an API call then it's from the website

2020-09-27 08:28 UTC, raj454raj approved these changes

2020-09-27 08:28 UTC, merged