Header set
stopstalk/stopstalk-deployment pull request #435
Opened 2020-12-13 09:20 UTC by manav1403

2020-12-13 13:14 UTC, raj454raj requested changes

2020-12-13 13:14 UTC, raj454raj commented on modules/utilities.py
> +        """
4 space indent

2020-12-14 10:13 UTC, manav1403 commented
@raj454raj pls review

2020-12-14 19:46 UTC, raj454raj approved these changes

2020-12-14 19:46 UTC, merged